name: nr
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - jax
  - tqdm
  - trimesh
  - vedo
  - graph-tool
  - scikit-learn
  - scikit-image
  - pyside6
  - ipykernel
  - pytest
  - pytest-cov
  - mypy
  - ruff
  - sphinx >=7
  - myst-parser
  - sphinx-autodoc-typehints
  - furo
  - sphinx-copybutton
  - pip:
      - -e .
