"""Low-level graph utility helpers."""

from .coordinates import (
    edge_coordinates,
    edge_coordinates_subtree,
    vertex_coordinates,
    vertex_coordinates_subtree,
)
from .counting import (
    count_bifurcations,
    count_branches,
    count_edges,
    count_leaves,
    count_roots,
    count_sections,
    count_transitive_vertices,
    count_vertices,
)
from .degrees import degree_distribution, get_vertex_degrees
from .graph_editing import reduce_graph, reroot_graph
from .gt_properties import (
    bind_edge_property,
    bind_graph_property,
    bind_vertex_property,
    del_property,
    g_has_property,
    get_property,
    list_properties,
    raise_internal_property_missing,
    revert_core_properties,
    set_property,
)
from .subgraphs import (
    extract_subgraph,
    max_subgraph_ind,
    partition_asymmetry,
    subgraph_score,
)
from .traversals import (
    AngleVisitor,
    PostOrderVisitor,
    ReduceVisitor,
    SubtreeMaskVisitor,
    TreeDepthVisitor,
    bf_iterator,
    bfsearch,
    df_iterator,
    dfsearch,
)
from .vertex_inds import (
    bifurcation_indices,
    branch_indices,
    core_indices,
    edge_indices,
    leaf_indices,
    root_index,
    subtree_indices,
)

__all__ = [
    "g_has_property",
    "raise_internal_property_missing",
    "bind_vertex_property",
    "bind_edge_property",
    "bind_graph_property",
    "revert_core_properties",
    "list_properties",
    "get_property",
    "set_property",
    "del_property",
    "root_index",
    "leaf_indices",
    "branch_indices",
    "core_indices",
    "edge_indices",
    "subtree_indices",
    "bifurcation_indices",
    "count_roots",
    "count_vertices",
    "count_edges",
    "count_leaves",
    "count_branches",
    "count_transitive_vertices",
    "count_sections",
    "count_bifurcations",
    "bfsearch",
    "bf_iterator",
    "dfsearch",
    "df_iterator",
    "TreeDepthVisitor",
    "PostOrderVisitor",
    "ReduceVisitor",
    "SubtreeMaskVisitor",
    "AngleVisitor",
    "vertex_coordinates",
    "vertex_coordinates_subtree",
    "edge_coordinates",
    "edge_coordinates_subtree",
    "reduce_graph",
    "reroot_graph",
    "subgraph_score",
    "max_subgraph_ind",
    "extract_subgraph",
    "partition_asymmetry",
    "get_vertex_degrees",
    "degree_distribution",
]
