name: Generate Sphinx Documentation

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Choose your Python version

      - name: Install sphinx
        run: |
            pip install sphinx sphinx-rtd-theme  # Install Sphinx and the Read the Docs theme

      - name: Build Sphinx documentation
        run: |
          cd docs
          make clean
          make html

          - name: Check for changes
          id: check_changes
          run: |
            git diff --quiet --exit-code build/html/          

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto-generate Sphinx documentation"
          git push
