name: lint

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          environment-name: nr
          create-args: >-
            -y

      - name: Ruff check
        shell: bash -l {0}
        run: ruff check src tests

      - name: Ruff format
        shell: bash -l {0}
        run: ruff format --check src tests
